Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

### jenkins-master vm  ####
  config.vm.define "jenkins-master" do |jm|
    jm.vm.box = "bento/ubuntu-24.04"
    jm.vm.hostname = "jenkins-master"
    jm.vm.disk :disk, size: "20GB", primary: true
    jm.vm.network "private_network", ip: "192.168.56.20"
    jm.vm.network "public_network"
    jm.vm.provider "virtualbox" do |vb|
     vb.memory = 2048
     vb.cpus = 1
   end
    jm.vm.provision "shell", path: "jenkins-master.sh"
  end

### jenkins-agent vm  ####
  config.vm.define "jenkins-agent" do |ja|
    ja.vm.box = "bento/ubuntu-24.04"
    ja.vm.hostname = "jenkins-agent"
    ja.vm.disk :disk, size: "10GB", primary: true
    ja.vm.network "private_network", ip: "192.168.56.21"
    ja.vm.network "public_network"
    ja.vm.provider "virtualbox" do |vb|
     vb.memory = 1024
     vb.cpus = 1
   end
    ja.vm.provision "shell", path: "jenkins-agent.sh"
  end

  # === k8s-control-plane ===
  config.vm.define "k8s-control-plane" do |node|
    node.vm.box = "bento/ubuntu-24.04"
    node.vm.hostname = "k8s-control-plane"
    node.vm.network "private_network", ip: "192.168.56.30"
    node.vm.network "public_network"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    node.vm.provision "shell", path: "k8s.sh"
  end

  # === k8s-worker-node ===
  config.vm.define "k8s-worker-node" do |node|
    node.vm.box = "bento/ubuntu-24.04"
    node.vm.hostname = "k8s-worker-node"
    node.vm.network "private_network", ip: "192.168.56.31"
    node.vm.network "public_network"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 10240
      vb.cpus = 3
    end
    node.vm.provision "shell", path: "k8s.sh"
  end

end