ingress:
  enabled: true
  className: "nginx"
  host: "dev.env"
  pathType: Prefix

  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

  rules:
    - path: /
      service: api-gateway
      port: 8080
