{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ $svc.image }}:{{ $svc.tag }}"
          ports:
            - containerPort: {{ $svc.port }}
          env:
            - name: EUREKA_INSTANCE_HOSTNAME 
              value: {{ $name }} 
---
{{- end }}
{{- end }}

